
version: '3.8'
services:
  app:
    image: dmalky47/blogapp:v1-release
    container_name: blogapp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVICE: postgres:5432
      CACHE_REDIS_PORT: 6379
      CACHE_REDIS_URL: redis://redis:6379/0
    ports:
      - '5000:5000'
    depends_on:
      - "postgres"
      - "redis"
    networks:
      - backend
      
  postgres:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5432
    ports:
      - '5432:5432'
    networks:
      - backend
      
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - backend
      
networks:
  backend:
    driver: bridge
